version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shelfseek_backend
    ports:
      - "8000:8000"
    env_file: ./.env

  frontend:
    build: ./app
    container_name: shelfseek_frontend
    ports:
      - "7777:7777"